name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@YOUR_EC2_IP "bash /home/ubuntu/deploy.sh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
